import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../../shared/api/client';
import { Button } from '../button/Button';
import { SelectField } from '../form/SelectField';
import { TextAreaField } from '../form/TextAreaField';
import { TextField } from '../form/TextField';
import { Modal } from '../modal/Modal';
import type { IndicatorRecord } from './types';

type Props = { open: boolean; schoolId?: number; classId?: number; studentId?: number; scopeLabel: string; year: number; onClose: () => void; onSaved: (record: IndicatorRecord) => Promise<void>; };

export function IndicatorRecordDialog({ open, schoolId, classId, studentId, scopeLabel, year, onClose, onSaved }: Props) {
  const [indicator, setIndicator] = useState('IDEB'); const [recordType, setRecordType] = useState('OBSERVED_RESULT'); const [scenarioName, setScenarioName] = useState(''); const [sourceReference, setSourceReference] = useState(''); const [assumptions, setAssumptions] = useState(''); const [value, setValue] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setIndicator('IDEB'); setRecordType('OBSERVED_RESULT'); setScenarioName(''); setSourceReference(''); setAssumptions(''); setValue(''); setError(''); } }, [open]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const record = await apiRequest<IndicatorRecord>('/pedagogical-monitoring/indicator-records', { method: 'POST', body: JSON.stringify({ indicator, recordType, schoolId: schoolId ?? null, classId: classId ?? null, studentId: studentId ?? null, academicYear: year, scenarioName, sourceReference, assumptions, value: Number(value) }) }); await onSaved(record); onClose(); } catch (exception) { setError(exception instanceof Error ? exception.message : 'Não foi possível registrar o indicador.'); } finally { setSaving(false); } }
  const nonOfficial = recordType !== 'OBSERVED_RESULT';
  return <Modal open={open} title="Registrar indicador" onClose={onClose} footer={<><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit" form="indicator-record-form" variant="primary" disabled={saving}>{saving ? 'Salvando...' : 'Registrar'}</Button></>}><form id="indicator-record-form" className="form-stack" onSubmit={submit}><p className="field__hint"><strong>Escopo:</strong> {scopeLabel}</p><div className="form-grid"><SelectField name="indicator" label="Indicador" value={indicator} onChange={(event) => setIndicator(event.target.value)} options={[{ value: 'IDEB', label: 'IDEB' }, { value: 'IDEPE', label: 'IDEPE' }]} /><SelectField name="recordType" label="Tipo" value={recordType} onChange={(event) => setRecordType(event.target.value)} options={[{ value: 'OBSERVED_RESULT', label: 'Resultado observado' }, { value: 'SIMULATION', label: 'Simulação não oficial' }, { value: 'PROJECTION', label: 'Projeção não oficial' }]} /><TextField name="indicatorYear" label="Ano de referência" value={year} disabled /><TextField name="indicatorValue" type="number" min="0" step="0.001" label="Valor" required value={value} onChange={(event) => setValue(event.target.value)} /></div><TextField name="scenarioName" label={recordType === 'OBSERVED_RESULT' ? 'Identificação do resultado' : 'Nome do cenário'} required value={scenarioName} onChange={(event) => setScenarioName(event.target.value)} /><TextAreaField name="sourceReference" label="Origem dos dados" hint="Informe documento, publicação, conjunto de entradas ou outra referência que permita rastrear o valor." required value={sourceReference} onChange={(event) => setSourceReference(event.target.value)} /><TextAreaField name="assumptions" label="Premissas/observações" value={assumptions} onChange={(event) => setAssumptions(event.target.value)} />{nonOfficial ? <p className="state-message"><strong>Simulação não oficial</strong><span>O KRINO não aplica fórmula oficial de IDEB/IDEPE neste registro. O valor informado será armazenado como cenário não oficial no escopo selecionado.</span></p> : <p className="state-message"><strong>Referência documentada</strong><span>O valor observado será identificado como referência documentada e manterá a origem informada.</span></p>}{error ? <p className="form-error">{error}</p> : null}</form></Modal>;
}
