import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../../shared/api/client';
import { Button } from '../button/Button';
import { SelectField } from '../form/SelectField';
import { TextField } from '../form/TextField';
import { Modal } from '../modal/Modal';
import type { Component, Professional, SchoolClass } from './types';

type Props = { open: boolean; schoolClass?: SchoolClass; professionals: Professional[]; components: Component[]; onClose: () => void; onSaved: () => void; };

export function ScheduleDialog({ open, schoolClass, professionals, components, onClose, onSaved }: Props) {
  const [componentId, setComponentId] = useState(''); const [professionalId, setProfessionalId] = useState(''); const [dayOfWeek, setDayOfWeek] = useState('1'); const [startTime, setStartTime] = useState('07:00'); const [endTime, setEndTime] = useState('07:50'); const [validFrom, setValidFrom] = useState(`${schoolClass?.academicYear ?? new Date().getFullYear()}-01-01`); const [validUntil, setValidUntil] = useState(''); const [error, setError] = useState('');
  useEffect(() => { setComponentId(components[0]?.id.toString() ?? ''); setProfessionalId(''); setDayOfWeek('1'); setValidFrom(`${schoolClass?.academicYear ?? new Date().getFullYear()}-01-01`); setValidUntil(''); setError(''); }, [open, schoolClass, components]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!schoolClass) return; setError(''); try { await apiRequest('/secretaria/schedules', { method: 'POST', body: JSON.stringify({ classId: schoolClass.id, componentId: Number(componentId), professionalId: professionalId ? Number(professionalId) : null, dayOfWeek: Number(dayOfWeek), startTime, endTime, validFrom, validUntil: validUntil || null }) }); onSaved(); onClose(); } catch (exception) { setError(exception instanceof Error ? exception.message : 'Não foi possível salvar o horário de aula.'); } };
  return <Modal open={open} title={`Novo horário · ${schoolClass?.name ?? ''}`} onClose={onClose} footer={<><Button type="button" onClick={onClose}>Cancelar</Button><Button type="submit" variant="primary" form="schedule-form">Salvar horário</Button></>}><form id="schedule-form" className="form-stack" onSubmit={submit}><SelectField name="componentId" label="Componente curricular" value={componentId} onChange={(event) => setComponentId(event.target.value)} options={components.map((component) => ({ value: component.id.toString(), label: component.name }))} required /><SelectField name="professionalId" label="Professor" value={professionalId} onChange={(event) => setProfessionalId(event.target.value)} options={[{ value: '', label: 'Sem professor definido' }, ...professionals.filter((professional) => professional.active).map((professional) => ({ value: professional.id.toString(), label: professional.name }))]} /><SelectField name="dayOfWeek" label="Dia da semana" value={dayOfWeek} onChange={(event) => setDayOfWeek(event.target.value)} options={[{ value: '1', label: 'Segunda-feira' }, { value: '2', label: 'Terça-feira' }, { value: '3', label: 'Quarta-feira' }, { value: '4', label: 'Quinta-feira' }, { value: '5', label: 'Sexta-feira' }, { value: '6', label: 'Sábado' }, { value: '7', label: 'Domingo' }]} /><div className="form-grid form-grid--2"><TextField name="startTime" label="Início" type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} required /><TextField name="endTime" label="Fim" type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} required /></div><div className="form-grid form-grid--2"><TextField name="validFrom" label="Vigente a partir de" type="date" value={validFrom} onChange={(event) => setValidFrom(event.target.value)} required /><TextField name="validUntil" label="Vigente até" type="date" value={validUntil} onChange={(event) => setValidUntil(event.target.value)} /></div>{error ? <p className="form-error" role="alert">{error}</p> : null}</form></Modal>;
}
